# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: frutiger_postgres
    environment:
      POSTGRES_USER: frutiger_user
      POSTGRES_PASSWORD: frutiger_password_2024
      POSTGRES_DB: frutiger_streaming
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
    restart: unless-stopped
    networks:
      - frutiger_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frutiger_user -d frutiger_streaming"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  frutiger_network:
    driver: bridge